/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as ProtectedPlaygroundIndexRouteImport } from './routes/_protected/playground/index'
import { Route as ProtectedCustomersIndexRouteImport } from './routes/_protected/customers/index'
import { Route as ProtectedCustomersCustomerIdRouteImport } from './routes/_protected/customers/$customerId'
import { Route as ProtectedCustomersNewIndexRouteImport } from './routes/_protected/customers/new/index'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedPlaygroundIndexRoute =
  ProtectedPlaygroundIndexRouteImport.update({
    id: '/playground/',
    path: '/playground/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCustomersIndexRoute = ProtectedCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCustomersCustomerIdRoute =
  ProtectedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCustomersNewIndexRoute =
  ProtectedCustomersNewIndexRouteImport.update({
    id: '/customers/new/',
    path: '/customers/new/',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/signin': typeof AuthSigninRoute
  '/customers/$customerId': typeof ProtectedCustomersCustomerIdRoute
  '/customers': typeof ProtectedCustomersIndexRoute
  '/playground': typeof ProtectedPlaygroundIndexRoute
  '/customers/new': typeof ProtectedCustomersNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/signin': typeof AuthSigninRoute
  '/customers/$customerId': typeof ProtectedCustomersCustomerIdRoute
  '/customers': typeof ProtectedCustomersIndexRoute
  '/playground': typeof ProtectedPlaygroundIndexRoute
  '/customers/new': typeof ProtectedCustomersNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_protected/customers/$customerId': typeof ProtectedCustomersCustomerIdRoute
  '/_protected/customers/': typeof ProtectedCustomersIndexRoute
  '/_protected/playground/': typeof ProtectedPlaygroundIndexRoute
  '/_protected/customers/new/': typeof ProtectedCustomersNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/signin'
    | '/customers/$customerId'
    | '/customers'
    | '/playground'
    | '/customers/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/signin'
    | '/customers/$customerId'
    | '/customers'
    | '/playground'
    | '/customers/new'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/signin'
    | '/_protected/customers/$customerId'
    | '/_protected/customers/'
    | '/_protected/playground/'
    | '/_protected/customers/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/playground/': {
      id: '/_protected/playground/'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof ProtectedPlaygroundIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/customers/': {
      id: '/_protected/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof ProtectedCustomersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/customers/$customerId': {
      id: '/_protected/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof ProtectedCustomersCustomerIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/customers/new/': {
      id: '/_protected/customers/new/'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof ProtectedCustomersNewIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedCustomersCustomerIdRoute: typeof ProtectedCustomersCustomerIdRoute
  ProtectedCustomersIndexRoute: typeof ProtectedCustomersIndexRoute
  ProtectedPlaygroundIndexRoute: typeof ProtectedPlaygroundIndexRoute
  ProtectedCustomersNewIndexRoute: typeof ProtectedCustomersNewIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCustomersCustomerIdRoute: ProtectedCustomersCustomerIdRoute,
  ProtectedCustomersIndexRoute: ProtectedCustomersIndexRoute,
  ProtectedPlaygroundIndexRoute: ProtectedPlaygroundIndexRoute,
  ProtectedCustomersNewIndexRoute: ProtectedCustomersNewIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
