import path from "path";
import { defineConfig } from "@hey-api/openapi-ts";
import { OUTPUT_DIR } from "./constant";

export default defineConfig({
  input: path.resolve(__dirname, "swagger.json"),
  output: {
    path: OUTPUT_DIR,
    /**
     * remove default header "This file is auto-generated by @hey-api/openapi-ts"
     */
    header: ({ file, meta, project, defaultValue }) => {
      switch (file?.name) {
        case "types":
          return 'import { Pagination } from "../common";';
        default:
          return null;
      }
    },
    fileName: {
      /**
       * remove file's suffix (e.g., .gen.ts)
       */
      suffix: null,
    },
    postProcess: [
      // TODO: enable postprocess pipeline as it needed
      // {
      //   command: "npx",
      //   args: ["tsx", path.resolve(__dirname, "postprocess-pipeline/index.ts")],
      // },
      "prettier",
    ],
  },
  parser: {
    filters: {
      // operations: {
      //   // only generate these operations
      //   include: [
      //     "GET /store/apps",
      //   ],
      // },
      //   // only generate these schemas
      // schemas: {
      //   include: ["QueryAppsResponse"],
      // },
    },
    hooks: {
      symbols: {
        /**
         * getExportFromFilePath - The file path(s) that re-export this symbol
         * getFilePath - The file path to output the symbol
         * getName - The name to register the symbol with run before defination
         */
      },
    },
    transforms: {
      /**
       * Enable required all by default if some field is nullable it will explicitly marked as optional in swagger
       */
      propertiesRequiredByDefault: true,
    },
    validate_EXPERIMENTAL: true,
  },
  plugins: [
    {
      // name: "zod",
      // compatibilityVersion: 3,
      name: "@hey-api/typescript",
      /**
       * Remove all comments
       */
      comments: false,
      definitions: {
        case: "PascalCase",
        name: (name: string) => {
          let result = name.replace(/Response$/, "");
          result = result.replace(/Dto$/, "");
          return result;
        },
      },
      responses: {
        case: "PascalCase",
        name: "{{name}}Response",
      },
      requests: {
        case: "PascalCase",
        name: "{{name}}Request",
      },
    },
  ],
});
